controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

reports_show_all:
    path: /api/v1/reports
    methods: [GET]
    controller: App\Controller\ReportController::showAll